version: '3'
services:
  postgres-user:
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=thutasann2002tts
      - POSTGRES_DB=test-api
    volumes:
      - ./docker-utils:/docker-entrypoint-initdb.d
      - test_api_data:/data/postgres
    ports:
      - 5432:5432
volumes:
  test_api_data: {}
