name: Node.js CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Change to nest-advanced
        run: cd nest-advanced

      - name: Install dependencies
        run: npm install
        working-directory: nest-advanced

      - name: PNPM Build All
        run: npm run build-all
        working-directory: nest-advanced
