name: Nestjs. CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Change to nest-advanced
        run: cd nest-advanced

      - name: Install pnpm
        run: npm install -g pnpm
        working-directory: nest-advanced

      - name: PNPM Install dependencies
        run: pnpm install
        working-directory: nest-advanced

      - name: Install Nx globally
        run: pnpm add -g nx
        working-directory: nest-advanced

      - name: Run Nx affected commands
        run: |
            nx affected:lint --all
            nx affected:test --all
            nx affected:build --all
        working-directory: nest-advanced