name: Node.js CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./app-backend/catalog_service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: yarn install --ignore-engines

      - name: List files for debugging
        run: ls -R

      - name: Generate Prisma client
        run: npx prisma generate --schema=./prisma/schema.prisma

      - name: Run Build Catalog
        run: yarn build
