name: Node.js CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Change directory to Backend
        run: cd app-backend

      - name: Change directory to Catalog Service
        run: cd catalog_service

      - name: Install dependencies
        run: yarn install --ignore-engines

      - name: List files for debugging
        run: ls -R

      - name: Generate Prisma client
        run: npx prisma generate --schema=./prisma/schema.prisma

      - name: Run Build Catalog
        run: |
          yarn build
