name: Node.js CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Change to catalog_service directory
        run: cd tiny-nest-next/app-backend/catalog_service

      - name: Install dependencies
        run: npm install
        working-directory: tiny-nest-next/app-backend/catalog_service

      - name: Generate Prisma client
        run: npx prisma generate
        working-directory: tiny-nest-next/app-backend/catalog_service

      - name: Build project
        run: npm run build
        working-directory: tiny-nest-next/app-backend/catalog_service
